/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 mac.gltf --transform 
Files: mac.gltf [1.17MB] > mac-transformed.glb [305.03KB] (74%)
Author: dylanheyes (https://sketchfab.com/dylanheyes)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ultrawide-monitor-f84d24b6df3648d884fd9be9c8007dd4
Title: Ultrawide Monitor
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/mac-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Ultrawide_Monitor_Screen_0.geometry} material={materials.Screen} rotation={[-Math.PI / 2, 0.001, -Math.PI / 2]} scale={[1, 10, 7]} />
      <mesh geometry={nodes.Ultrawide_Monitor_Body_0.geometry} material={materials.Body} rotation={[-Math.PI / 2, 0.001, -Math.PI / 2]} scale={[0.194, 10, 7]} />
      <mesh geometry={nodes.Ultrawide_Monitor_Lights_0.geometry} material={materials.Lights} rotation={[-Math.PI / 2, 0.001, -Math.PI / 2]} scale={[0.194, 10, 7]} />
    </group>
  )
}

useGLTF.preload('/mac-transformed.glb')
